(define 
  (problem conveyor-high-stack-6)
  (:domain conveyor-transfer-domain)
  (:objects
    a b c d e f - block
    temp temp2 goal - location)
  (:init 
    (conveyor_pickable a)
    (at 2 (not (conveyor_pickable a)))
    (at 10 (conveyor_pickable b))
    (at 12 (not (conveyor_pickable b)))
    (at 20 (conveyor_pickable c))
    (at 22 (not (conveyor_pickable c)))
    (at 30 (conveyor_pickable d))
    (at 32 (not (conveyor_pickable d)))
    (at 40 (conveyor_pickable e))
    (at 42 (not (conveyor_pickable e)))
    (at 50 (conveyor_pickable f))
    (at 52 (not (conveyor_pickable f)))
    (clear temp)
    (clear temp2)
    (clear goal)
    (handempty))
  (:goal (and
    (at f goal)
    (at e f)
    (at d e)
    (at c d)
    (at b c)
    (at a b)
    (off_conveyor a)
    (off_conveyor b)
    (off_conveyor c)
    (off_conveyor d)
    (off_conveyor e)
    (off_conveyor f)
  ))

)
